src/client/components/RecentCampaignsChartWidget/RecentCampaigns.react.js
src/client/components/TotalSummaryWidget/TotalSummary.react.js
src/client/containers/CampaignDashboard.react.js

https://github.com/OpusCapita/onboarding/issues/103

Working TotalSummaryWidget

---

src/server/templates/ncc_onboard.handlebars

Register functionality has to be moved from user service to auth service. Involved repositories:
- user (see user#32)
- auth (see auth#34)
- api-gw (see api-gw#20)
- onboarding (link in ncc-email had to be adjusted)
**Steps that we have to walk through**
1. api-gw: Grant access to new resources for the new auth services.
2. user: Provide new endpoints for usage from auth.
3. auth: Introduce new registration endpoints.
4. onboarding: Adjust urls to new registration endpoints.
5. api-gw: Remove old register resources from ACL.
6. user: Remove deprecated registration endpoints.

Refactoring register - Step 4

---

README.md
src/server/workflow/workflow.js

I did three things here
- fix db snafu with event listener updating supplierId on ALL contacts in status registered
- add docs in Readme (about the status in the contact workflow)
- add the actual voucher code generation

adding voucher generation, docs, fixing db snafu

---

src/server/workflow/workflow.js

endpoint for voucher generation is einvoice-send/api/config/voucher

fixed voucher and notification generation calls

---

src/client/containers/CampaignDashboard.react.js
src/sharedComponents/funnelChart/component.js
src/webpack/webpack.base.config.js

another shared component fix

---

src/client/actions/campaignContacts/load.js
src/client/actions/campaigns/getAll.js

notifications removed from dashboard

---

package.json
src/client/containers/CampaignDashboard.react.js
src/server/templates/index.handlebars
src/sharedComponents/funnelChart/component.js
src/webpack/webpack.base.config.js
src/webpack/webpack.config.js
src/webpack/webpack.development.config.js
src/webpack/webpack.production.config.js

Shared.component window.main

---

src/server/static/css/ocui-bootstrap-bundle-0.1.2.css

datepicker style update

---

src/client/components/CampaignContacts/ContactForm.react.js

supplierId - disabled or hidden field

---

src/server/routes/campaignContact.js

query enhancement

---

src/server/routes/campaignContactImport.js

There was no Promise.reject() to add new Error object to it.

added bluebird promise library to src/routes/campaignContactImport.js

---

src/server/routes/campaign.js

Campaign search fix

---

src/server/routes/campaign.js

direct edit url working

---

src/server/routes/campaign.js

updated query for put campaign request

---

src/server/static/css/ocui-bootstrap-bundle-0.1.2.css

calendar displaying - fix

---

src/client/containers/CampaignDashboard.react.js

removed loop pulling contacts at CampaignDashboard

---

src/server/templates/eInvoiceSupplierOnboarding/generic_landingpage.handlebars
src/server/templates/eInvoiceSupplierOnboarding/generic_landingpage_de.handlebars

https://github.com/OpusCapita/onboarding/issues/354

Adjusted the manual path to a version independen one

---

src/server/routes/campaign.js

#368 - CampaignContact - Export: No response

Update supplierId field name #368

---

src/server/routes/campaign.js

Remove fallbacks to ncc #364

---

src/server/db/migrations/20170914123200-add-created-and-changed-fields.main.js
src/server/db/models/Campaign.js
src/server/routes/campaign.js
src/server/routes/campaignContact.js

Campaign, CampaingContacts: add created and changed fields

---

src/server/db/models/Campaign.js
src/server/routes/index.js
src/server/templates/eInvoiceSupplierOnboarding/email/generic.handlebars

email - view it in your browser

---

Dockerfile
docker-compose.override.yml
package.json
src/client/components/CampaignContacts/CampaignContactEditor.react.js
src/server/routes/campaignContact.js
src/server/utils/export.js
src/server/workflow/workflow.js

export fix and initial debug configuration

---

src/server/workflow/workflow.js

#396
Pretty straight forward. Because all other checks are done, the transition replacement can be easily with OR.

(396) Added implicit loaded transition
